steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t','gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']  
  - name: 'node:18.16.1'  # Updated to Node.js version 18.16.1
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18.16.1'  # Updated to Node.js version 18.16.1
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase' 
    args: ['use', '${_FIREBASE_PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'  
    args: ['target:apply', 'hosting', 'biblioinsights-12d09', 'biblioinsights-12d09', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'  
    args: ['deploy', '--token','${_FIREBASE_TOKEN}', '--only', 'hosting:biblioinsights-12d09']
    timeout: 1200s
